config/routes.rb
Rails.application.routes.draw do
  resources :publications
  devise_for :users
  post '/new_user_reaction', to: 'reactions#new_user_reaction', as: 'new_user_reaction'
  resources :comments, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "publications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publication
  belongs_to :user
  # Start *TODO: "Relacionar las tablas en los modelos"
  has_many :reactions, dependent: :destroy
  # End *TODO: ""
end

app/models/publication.rb
class Publication < ApplicationRecord
    # Start *TODO: "Relacionar las tablas en los modelos"
    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy
    has_many :users, through: :reactions

    # Me gusta o no me gusta
    Kinds = %w[like dislike].freeze
    KindsSpanish = {"like" => "Me gusta", "dislike" => "No me gusta"}.freeze

    # End *TODO: ""
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  # Start *TODO: "optional: true, la migración no tengan null: false"
  belongs_to :publication, optional: true
  belongs_to :user
  belongs_to :comment, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Start *TODO: "Relacionar las tablas en los modelos"
  has_many :reactions
  has_many :comments
  has_many :publications, through: :reactions
  # End *TODO: ""

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Start *TODO: "Agregamos strong params"
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
    end
    # End *TODO: "strong params"
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # Start *TODO: "Controlador de creación de comentarios"
    def create
        @publication = Publication.find(params[:comment][:publication_id])
        @comment = Comment.new(comment_params)
        @comment.user = current_user

        respond_to do |format|
            if @comment.save
              format.html { redirect_to publication_path(@publication.id), notice:'Comment was successfully created.' }
            else
              format.html { redirect_to publication_path(@publication.id), notice:'Comment was not created.' }
            end
        end
    end

    private
    def comment_params
      params.require(:comment).permit(:content, :publication_id)
    end
    # End *TODO: ""
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    # Start *TODO: "Agregamos comentarios"
    @comment = Comment.new
    # Start *TODO: "Agregamos comentarios para mostrarlos"
    @comments = @publication.comments
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :description)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    # Start *TODO: "Agregamos controlador"
    def new_user_reaction
        @user = current_user
        @type = params[:reaction_type]
        @publication = Publication.find(params[:publication_id]) if params[:publication_id]
        @comment = Comment.find(params[:comment_id]) if params[:comment_id]
        @kind = params[:kind]

        respond_to do |format|
            (@type == "comment") ? reaction_comment = Reaction.find_by(user_id: @user,
                comment_id: @comment.id) : reaction_publication = Reaction.find_by(user_id: @user.id, publication_id: @publication.id)

                if reaction_publication || reaction_comment
                  format.html { redirect_to publication_path(@publication), notice: 'You already reacted to this publication' }
                else
                  (@type == "publication") ? @reaction = Reaction.new(user_id: @user.id, publication_id:
                  @publication.id, reaction_type: @type, kind: @kind) : @reaction = Reaction.new(user_id:
                  @user.id, comment_id: @comment.id, reaction_type: @type, kind: @kind)
                if @reaction.save!
                  format.html { redirect_to publication_path(@publication), notice: 'Reaction was successfully created.' }
                else
                  format.html { redirect_to publication_path(@publication), notice: 'Something went wrong' }
                end
                
            end
        end
    end
    # End *TODO: ""
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/_article_comments.html.erb
<!-- Start *TODO: "Agregamos comentarios a la vista show del artículo" -->
<div class="container">
    <% @comments.each do |comment| %>
        <p class="subtitle">
            <div class="owner-avatar">
              <%= image_tag comment.user.photo, class: 'rounded-circle', style: "width:45px; height:45px;"  %>
            </div>
            <strong>Comentario: </strong><%= comment.content %>
        </p>
    <% end %>
</div>
<!-- End *TODO: "" -->

app/views/comments/_form.html.erb
<!-- Start *TODO: "Agregar formulario de comentarios a vista show de artículos -->
<%= form_with(model: @comment, local: true) do |f| %>
    <% if @comment.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este comentario no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @comment.errors.full_messages.each do |msg|%>
                  <li><%= msg %></li>
                <% end %>
            </ul>
        </div> 
    <% end %>
    <%= f.hidden_field :publication_id, value: @publication.id %>
    <div class = 'field'>
        <%= f.label :content, "Contenido", class:"form-label" %>
        <div class="control">
          <%= f.text_field :content, class:"form-control"  %>
        </div>
    </div>
    <br>
    <div class = 'actions'>
      <%= f.submit class:"btn btn-primary" %>
    </div>
<% end %>
<!-- End *TODO: "" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- *TODO: "Agregamos bootstrap 5.3" -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <div class="container">
      <%= yield %>
    </div>

    <br><br><br>
    <br><br><br>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Titulo", class:"form-label", style: "display: block" %>
    <%= form.text_field :title, class:"form-control", placeholder:"Titulo" %>
  </div>

  <div class="field">
    <%= form.label :description, "Descripcion", class:"form-label", style: "display: block" %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <br />
  <div class="field">
    <div class="control">
      <%= form.submit class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">

  <div class="card">
    <div class="card-header">
      <p class="subtitle">
        <strong>Titulo:</strong>
        <span class="tag is-light is-medium"><%= publication.title %></span>
      </p>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p class="subtitle">
          <strong>Descripcion:</strong>
          <%= publication.description %>
        </p>
        <footer class="blockquote-footer">
          <p class="subtitle">
            <strong>Publicado:</strong>
            <cite title="Source Title"><%= publication.created_at %></cite>
          </p>
        </footer>
      </blockquote>
    </div>
  </div>

</div>

app/views/publications/edit.html.erb
<br>
<h2 class="title"><mark>Editar Publicacion</mark></h2>
<br>
<div class="card text-bg-light ">
  <div class="card-body">
    <%= render "form", publication: @publication %>
  </div>
</div>

<hr>

<div>
  <%= link_to "Ver Publicacion", @publication, class:"btn btn-info" %> 
  <%= link_to "Volver", publications_path, class:"btn btn-light" %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<br>
<h2 class="h2"><mark>Publicaciones</mark></h2>
<br>
<%= link_to "Nueva publicacion", new_publication_path, class:"btn btn-primary" %>
<hr>

<div id="publications" class="container">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <br>
    <p class="subtitle">
      <%= link_to "Ver mas", publication, class:"btn btn-info" %>
    </p>
  <% end %>
</div>

app/views/publications/new.html.erb
<br>
<h2 class="title"><mark>Nueva Publicacion</mark></h2>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Volver", publications_path, class:"btn btn-light" %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<br>

<h2 class="title"><mark>Publicacion</mark></h2>
<br>
<%= render @publication %>

<br>

<!-- Start *TODO: "Agregar botón para crear reacción en vista show del artículo" -->
<div class="container">
  <% Publication::Kinds.each do |kind| %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end ">
        <%= button_to "#{Publication::KindsSpanish[kind]}", new_user_reaction_path(publication_id: @publication.id, reaction_type: "publication", kind: kind), method: :post, class:"btn btn-outline-primary btn-sm" %>
    </div>
    <br>
  <% end %>
</div>
<!-- End *TODO: "" -->

<br>
<!-- Start *TODO: "comentarios a vista show" -->

  <div class="card">
    <div class="card-content">
      <div class="content">
        <div class="container">
          <strong>Realizar Comentario:</strong> <%= render 'comments/form' %>
        </div>
      </div>
    </div>
  </div>

<br>



<hr>
<div class="container">
  <strong><mark>Comentarios:</mark></strong>
  <div class="card text-bg-light ">
  <div class="card-body">
    <%= render 'comments/article_comments' %>
  </div>
</div>
</div>
<hr>

<div class = "btn-group">
  <%= link_to "Editar", edit_publication_path(@publication), class:"btn btn-warning" %> 
  <%= link_to "Volver", publications_path, class:"btn btn-light" %>
  <%= button_to "Eliminar", @publication, method: :delete, class:"btn btn-danger" %>
</div> 

<br>
<br>

app/views/shared/_footer.html.erb
<footer class="text-center text-white fixed-bottom" style="background-color: #21081a;">
  <!-- Grid container -->
  <div class="container p-4"></div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright: Victor Valenzuela B. | Power By Ruby on Rails
    <a class="text-white" href="">Crazy4Cats.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">

         
        <%= image_tag 'blackcat.png', class: 'rounded-circle', style:"width:45px; height:45px;" %>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">

                    <%= link_to 'Crazy4Cats', root_path, class: 'navbar-brand' %>
                   
                </li>
                <li class="nav-item">

                    
                   
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">

                    <% if user_signed_in? %>
                        <% if current_user.email %>
                          Bienvenido <%= image_tag current_user.photo, class: 'rounded-circle', style: "width:25px; height:25px;"  %> <%= current_user.email %> 
                        <% else %>
                          Bienvenido <%= current_user.name %>
                        <% end %>
                    <% else %>    
                        Registrate / Conectate
                    <% end %>

                    </a>
                    <ul class="dropdown-menu">
                        <% if user_signed_in? %>
                            <li>
                                <%= link_to 'Editar perfil',  edit_user_registration_path, class: 'dropdown-item' %>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
                            </li>
                        <% else %>
                            <li>
                                <%= link_to 'Iniciar sesión',  new_user_session_path, class: 'dropdown-item'%>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <%= link_to 'Registro',  new_user_registration_path, class: 'dropdown-item'%>
                            </li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>